### PR TITLE
Fix issue #45

### PR DESCRIPTION
**Pull request by gskachkov**
Fix issue #45, just change of the order values array that passed into _execCommand function.

### CODE REVIEW

**Comment by mthenw** [comment]
+1

**Comment by wvankuipers** [comment]
:+1:

**Comment by k0nG** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
Thanks and sorry for the late reply. Could you please update the commit message following our [convention](karma-runner.github.io/0.12/dev/git-commit-msg.html) so we can get this merged? Thanks.

**Comment by Dignifiedquire** [comment]
Fixed in #91

**Pull request closed without merging**
