### PR TITLE
Adding console output to phantomjs

### LINKED ISSUE #18: Log errors from the browser
https://github.com/ariya/phantomjs/wiki/Troubleshooting#error-handling

```js
page.onError = function (msg, trace) {
    console.log(msg);
    trace.forEach(function(item) {
        console.log('  ', item.file, ':', item.line);
    })
}
```

### PR DESCRIPTION
**Pull request by park9140**
Adding ability for phantomjs standard error and stdout to be pushed to console.  Also logging browser console messages to stdout.

Resolves #18 partially.

### CODE REVIEW

**Comment by gonsfx** [comment]
Could help with #67

**Comment by Dignifiedquire** [comment]
Could you please update the commit message following our [convention](karma-runner.github.io/0.12/dev/git-commit-msg.html) ?

**Comment by park9140** [comment]
@Dignifiedquire, I'll do it tomorrow if I have time.  Just tried and apparently sometime between last year and now my access to the particular fork was revoked... :(

**Comment by park9140** [comment]
@Dignifiedquire, I updated to match what looks like the convention.

**Comment by Dignifiedquire** [comment]
Thanks @park9140. 

LGTM

**Comment by park9140** [comment]
@Dignifiedquire I resolved the merge conflict on this change.

**Comment by park9140** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by martinsson** [comment]
Hi,

this only solves the problem when setting  logLevel: config.LOG_DEBUG,
which is not feasible all the time.

Basically swallowed log happens when the error happens after the spec execution. To reproduce
        fit('swallowed error', function(done) {
            var undefinedSomething
            var doneDelay = 500;
            setTimeout(function () {
                undefinedSomething.toto()
                throw new Error("shoudl catch this in console")
            }, doneDelay+100)

            setTimeout(function () {
                done()
            }, doneDelay)

        })

Now I tried to add a page.onError function to capture.js but even if I propagate the error to console.error it will be still be send in stdout, is the clause in index.js that catches it : 
    this._process.stdout.on('data', function (data) {
      log.debug('' + data)
    })

still does log.debug. 

I see two solutions. 

1. Send it to _process.stderr from capture.js but I have no idea how
2. search data in index.js to see if it contains the string /Error/ and then do a log.warn(data)

I would much prefer 1, but I'm gonna hack the second solution for now. Anyone could help me with a better solution?

**Pull request merged**
